version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    commit-message:
      prefix: 'deps[npm]: '
    schedule:
      day: 'saturday'
      interval: 'weekly'
      time: '06:00'
  - package-ecosystem: github-actions
    directory: '/'
    commit-message:
      prefix: 'deps[ci]: '
    schedule:
      day: 'saturday'
      interval: 'weekly'
      time: '06:05'